name:  Kinjo-market-backend 

on:
  push:
    branches:
      - main

jobs:
  test_new_merge_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java 
        uses: actions/setup-java@v4
        with:
           distribution: 'zulu' 
           java-version: '21'
           cache: 'maven'
           cache-dependency-path: './pom.xml'
           
      - name: Build the app
        run: mvn clean package
      
  deploy_to_server:
    runs-on: ubuntu-latest
    needs: test_new_merge_changes
    steps:
      - name:  Ssh into prod server 
        env:
          GIT_USER:  ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.KINJO_BACKEND_SSH_PASS }}
          port: ${{ secrets.PORT }}
          envs: GIT_USER,GIT_TOKEN

          script: |
            cd Beauthrist-Backend/Beauthrist-Backend
            git pull "https://$GIT_USER:$GIT_TOKEN@github.com/$GIT_USER/kinjomarket-prod-backend.git
            mvn clean package 
            sudo systemctl restart kinjomarket.service
      
