name:  Kinjo-market-backend 

on:
  push:
    branches:
      - main

jobs:
  test_new_merge_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java 
        uses: actions/setup-java@v4
        with:
           distribution: 'zulu' 
           java-version: '21'
           cache: 'maven'
           cache-dependency-path: './pom.xml'
      - run: mvn clean package
      
  deploy_to_server:
    runs-on: ubuntu-latest
    needs: test_new_merge_changes
    steps:
      - name: Install dependencies
      - run: |
          sudo apt update
          sudo apt install sshpass -y 
      - name:  Ssh into prod server 
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PASS: ${{ secrets.KINJO_BACKEND_SSH_PASS }}

        run: |
          sshpass -p "$SERVER_PASS" $SERVER_USER@$SERVER_HOST

      - name: Navigate Directory
      - run: |
          cd Beauthrist-Backend/Beauthrist-Backend

      - name: Pull New Changes
        env:
          GIT_USER:  ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git pull "https://$GIT_USER:$GIT_TOKEN@github.com/$GIT_USER/kinjomarket-prod-backend.git

      - name: Build The Jar file
        run: |
          mvn clean package 

      - name: Deploy to live 
        run: |
          sudo systemctl restart kinjomarket.service
      
